[package]
name    = "symbiotic-clipboard"
version = "0.1.0"
authors = ["meh. <meh@schizofreni.co>"]

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies.docopt_macros]
#git = "https://github.com/docopt/docopt.rs.git"
git = "https://github.com/kinghajj/docopt.rs.git"
branch = "fixes"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs.git"

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl.git"

[[bin]]
name = "symbiotic-clipboard"
