port  = 42231
hosts = ["192.168.1.2", "192.168.1.3"]
mode  = "both" # "outgoing" and "incoming" are the alternatives

[platform]
display = ":0.0"
mode    = "selection" # "clipboard" is the alternative
